info:
  _postman_id: f3a140ee-b420-4d2d-846a-ab6251e0291a
  name: swagger_getProduct
  schema: https://schema.getpostman.com/json/collection/v2.1.0/collection.json
  _exporter_id: '24318499'
item:
  - name: localhost:8080/products
    request:
      method: GET
      header: []
      url:
        raw: localhost:8080/products
        host:
          - localhost
        port: '8080'
        path:
          - products
          
          
    response: []